/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MafiaFactory } from "./MafiaFactory";
export type { Ownable } from "./Ownable";

export { MafiaFactory__factory } from "./factories/MafiaFactory__factory";
export { Ownable__factory } from "./factories/Ownable__factory";
